services:
  - type: web
    name: persona-doc-api
    env: python
    buildCommand: pip install -r week_09/requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker week_09.persona_doc.main:app
    envVars:
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: nexus-churn-api
    env: python
    buildCommand: pip install -r customer-churn-predictor/backend/requirements.txt
    startCommand: cd customer-churn-predictor/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false